spring:
  mail:
    host: smtp.gmail.com
    username: xatzic8@gamil.com
    password: Eimaiokaluteros007
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true